site_name: My site
site_url: https://mydomain.org/mysite

repo_url: https://github.com/PageotD/runmd
repo_name: pageotd/runmd

theme:
  logo: static/runmd.svg
  favicon: static/favicon.png
  icon:
    repo: fontawesome
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: green
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: green
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  icon:
    repo: simple/github
