# Debian Slim-based Dockerfile

# Use Debian Slim as the base image
FROM debian:stable-slim

# Install required packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    nodejs \
    npm \
    perl \
    python3 \
    python3-pip \
    ruby \
    && rm -rf /var/lib/apt/lists/*

# Create a symlink for python3 to python
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set bash as the default shell
CMD ["/bin/bash"]
