name: RunMD CI/CD

on:
  push:
    branches:
      - 'main'  # Runs for every commit on any branch
    tags:
      - '*.*.*'  # Runs for tag pushes
    paths:
      - 'src/runmd/**'  # Only triggers when files under cmd/taskido/ are modified
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - 'main'

jobs:
  # Build the package
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prep environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install build dependancies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest pytest-cov

      - name: Build package
        run: python -m build

      - name: Upload dist directory
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: List dist directory
        run: ls -R dist

  # Test package
  tests:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download dist directory
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Prep environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tests dependancies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest pytest-cov

      - name: Test package
        run: pip install dist/*.whl

      - name: Run tests
        run: pytest --cov=runmd tests

  # Release the package on Github
  release:
    runs-on: ubuntu-latest
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Download dist directory
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: List dist directory
        run: ls -R dist/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
